// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for External Links documents */
interface ExternalLinksDocumentData {
    /**
     * External Link field in *External Links*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: external_links.external_link[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    external_link: prismicT.GroupField<Simplify<ExternalLinksDocumentDataExternalLinkItem>>;
}
/**
 * Item in External Links → External Link
 *
 */
export interface ExternalLinksDocumentDataExternalLinkItem {
    /**
     * Label field in *External Links → External Link*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: external_links.external_link[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * link field in *External Links → External Link*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: external_links.external_link[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * icon field in *External Links → External Link*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: external_links.external_link[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
}
/**
 * External Links document from Prismic
 *
 * - **API ID**: `external_links`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExternalLinksDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ExternalLinksDocumentData>, "external_links", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Page Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * Page Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_description: prismicT.KeyTextField;
    /**
     * Page Keywords field in *Page*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_keywords[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    page_keywords: prismicT.GroupField<Simplify<PageDocumentDataPageKeywordsItem>>;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Item in Page → Page Keywords
 *
 */
export interface PageDocumentDataPageKeywordsItem {
    /**
     * keyword field in *Page → Page Keywords*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_keywords[].keyword
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keyword: prismicT.KeyTextField;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HeroV1Slice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = ExternalLinksDocument | PageDocument;
/**
 * Primary content in HeroV1 → Primary
 *
 */
interface HeroV1SliceDefaultPrimary {
    /**
     * Name field in *HeroV1 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_v1.primary.name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Designation field in *HeroV1 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_v1.primary.designation
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    designation: prismicT.KeyTextField;
    /**
     * Display Picture field in *HeroV1 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_v1.primary.display_picture
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    display_picture: prismicT.ImageField<never>;
}
/**
 * Item in HeroV1 → Items
 *
 */
export interface HeroV1SliceDefaultItem {
    /**
     * Label field in *HeroV1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_v1.items[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Link field in *HeroV1 → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_v1.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Icon field in *HeroV1 → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_v1.items[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
}
/**
 * Default variation for HeroV1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroV1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroV1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroV1SliceDefaultPrimary>, Simplify<HeroV1SliceDefaultItem>>;
/**
 * Slice variation for *HeroV1*
 *
 */
type HeroV1SliceVariation = HeroV1SliceDefault;
/**
 * HeroV1 Shared Slice
 *
 * - **API ID**: `hero_v1`
 * - **Description**: `HeroV1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroV1Slice = prismicT.SharedSlice<"hero_v1", HeroV1SliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ExternalLinksDocumentData, ExternalLinksDocumentDataExternalLinkItem, ExternalLinksDocument, PageDocumentData, PageDocumentDataPageKeywordsItem, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, HeroV1SliceDefaultPrimary, HeroV1SliceDefaultItem, HeroV1SliceDefault, HeroV1SliceVariation, HeroV1Slice };
    }
}
