// Code generated by Slice Machine. DO NOT EDIT.

import AboutMe from "./AboutMe";
import ContactOptions from "./ContactOptions";
import Experiences from "./Experiences";
import HeroV1 from "./HeroV1";
import QuickCards from "./QuickCards";
import SkillRatings from "./SkillRatings";

export {
  AboutMe,
  ContactOptions,
  Experiences,
  HeroV1,
  QuickCards,
  SkillRatings,
};

export const components = {
  about_me: AboutMe,
  contact_options: ContactOptions,
  experiences: Experiences,
  hero_v1: HeroV1,
  quick_cards: QuickCards,
  skill_ratings: SkillRatings,
};
