// Code generated by Slice Machine. DO NOT EDIT.

import AboutMe from "./AboutMe";
import HeroV1 from "./HeroV1";

export { AboutMe, HeroV1 };

export const components = {
  about_me: AboutMe,
  hero_v1: HeroV1,
};
